name: terraform apply
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
    - id: github_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: GOOGLE_PROJECT_ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: terraform version
      id: terraform-version
      run: echo "::set-output name=version::$(cat .terraform-version)"

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ steps.terraform-version.outputs.version }}

    - name: terraform init
      id: init
      run: terraform init

    - name: terraform refresh
      run: terraform refresh -parallelism=100 -compact-warnings
      env:
        GITHUB_TOKEN: ${{ steps.github_token.outputs.token }}

    - name: terraform apply
      id: apply
      run: terraform apply -no-color -compact-warnings -refresh=false -auto-approve
      env:
        GITHUB_TOKEN: ${{ steps.github_token.outputs.token }}

    - name: comment apply result
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          ## [${{ github.workflow }} #${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          <details>
          <summary>result</summary>

          ```hcl
          ${{ steps.apply.outputs.stdout }}
          ${{ steps.apply.outputs.stderr }}
          ```

          </details>
      if: always()
